version: '3'
services:
  flink-web:
    build: ./build
    image: flink-web:flink-1.14.6-20221025
    ports:
    - "9084:9084"
    - "5007:5007"
    - "8081:8081"
#    volumes:
#      - ./flink_web_conf/:/data/projects/flink-streaming-platform-web/conf/
    links:
    - mysql-web
  mysql-web:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flink_web_docker
    volumes:
      - ./mysql_data:/var/lib/mysql